services:
  - type: web
    name: ai-analytics-dashboard
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GROQ_API_KEY
        sync: false  # This will be set manually in Render dashboard
      - key: LANGSMITH_API_KEY
        sync: false  # Optional - set manually if needed
      - key: LANGSMITH_PROJECT
        value: ai-analytics-dashboard
    healthCheckPath: /health
    domains:
      - ai-analytics-dashboard.onrender.com  # You can customize this
    autoDeploy: true
    branch: main  # or your default branch name